export const wordsDB = {
  "1": [
    {"word": "apple", "phonetic": "/ˈæpəl/", "meaning": "苹果", "sentence": "I like apples."},
    {"word": "cat", "phonetic": "/kæt/", "meaning": "猫", "sentence": "The cat is cute."},
    {"word": "dog", "phonetic": "/dɒɡ/", "meaning": "狗", "sentence": "I have a dog."},
    {"word": "egg", "phonetic": "/eɡ/", "meaning": "鸡蛋", "sentence": "I eat an egg every day."},
    {"word": "fish", "phonetic": "/fɪʃ/", "meaning": "鱼", "sentence": "The fish can swim."},
    {"word": "girl", "phonetic": "/ɡɜːrl/", "meaning": "女孩", "sentence": "She is a good girl."},
    {"word": "hand", "phonetic": "/hænd/", "meaning": "手", "sentence": "Wash your hands."},
    {"word": "ice", "phonetic": "/aɪs/", "meaning": "冰", "sentence": "The ice is cold."},
    {"word": "juice", "phonetic": "/dʒuːs/", "meaning": "果汁", "sentence": "I like orange juice."},
    {"word": "kite", "phonetic": "/kaɪt/", "meaning": "风筝", "sentence": "Let's fly a kite."},
    {"word": "lion", "phonetic": "/ˈlaɪən/", "meaning": "狮子", "sentence": "The lion is strong."},
    {"word": "milk", "phonetic": "/mɪlk/", "meaning": "牛奶", "sentence": "I drink milk every morning."},
    {"word": "nose", "phonetic": "/noʊz/", "meaning": "鼻子", "sentence": "Touch your nose."},
    {"word": "orange", "phonetic": "/ˈɒrɪndʒ/", "meaning": "橙子", "sentence": "The orange is sweet."},
    {"word": "pen", "phonetic": "/pen/", "meaning": "钢笔", "sentence": "This is my pen."},
    {"word": "queen", "phonetic": "/kwiːn/", "meaning": "女王", "sentence": "She is the queen."},
    {"word": "red", "phonetic": "/red/", "meaning": "红色", "sentence": "The apple is red."},
    {"word": "sun", "phonetic": "/sʌn/", "meaning": "太阳", "sentence": "The sun is bright."},
    {"word": "tree", "phonetic": "/triː/", "meaning": "树", "sentence": "There is a big tree."},
    {"word": "umbrella", "phonetic": "/ʌmˈbrelə/", "meaning": "雨伞", "sentence": "Take your umbrella."},
    {"word": "van", "phonetic": "/væn/", "meaning": "面包车", "sentence": "The van is white."},
    {"word": "water", "phonetic": "/ˈwɔːtər/", "meaning": "水", "sentence": "I drink water."},
    {"word": "box", "phonetic": "/bɒks/", "meaning": "盒子", "sentence": "Put it in the box."},
    {"word": "yellow", "phonetic": "/ˈjeloʊ/", "meaning": "黄色", "sentence": "The banana is yellow."},
    {"word": "zoo", "phonetic": "/zuː/", "meaning": "动物园", "sentence": "Let's go to the zoo."},
    {"word": "book", "phonetic": "/bʊk/", "meaning": "书", "sentence": "I read a book."},
    {"word": "cake", "phonetic": "/keɪk/", "meaning": "蛋糕", "sentence": "The cake is yummy."},
    {"word": "duck", "phonetic": "/dʌk/", "meaning": "鸭子", "sentence": "The duck can swim."},
    {"word": "eye", "phonetic": "/aɪ/", "meaning": "眼睛", "sentence": "I have two eyes."},
    {"word": "foot", "phonetic": "/fʊt/", "meaning": "脚", "sentence": "I hurt my foot."}
  ],
  "2": [
    {"word": "bag", "phonetic": "/bæɡ/", "meaning": "书包", "sentence": "My bag is blue."},
    {"word": "big", "phonetic": "/bɪɡ/", "meaning": "大的", "sentence": "The elephant is big."},
    {"word": "bird", "phonetic": "/bɜːrd/", "meaning": "鸟", "sentence": "The bird can fly."},
    {"word": "bread", "phonetic": "/bred/", "meaning": "面包", "sentence": "I eat bread for breakfast."},
    {"word": "brother", "phonetic": "/ˈbrʌðər/", "meaning": "兄弟", "sentence": "He is my brother."},
    {"word": "candy", "phonetic": "/ˈkændi/", "meaning": "糖果", "sentence": "I like candy."},
    {"word": "chair", "phonetic": "/tʃer/", "meaning": "椅子", "sentence": "Sit on the chair."},
    {"word": "chicken", "phonetic": "/ˈtʃɪkɪn/", "meaning": "鸡", "sentence": "I like chicken."},
    {"word": "cloud", "phonetic": "/klaʊd/", "meaning": "云", "sentence": "Look at the cloud."},
    {"word": "cold", "phonetic": "/koʊld/", "meaning": "冷的", "sentence": "It is cold today."},
    {"word": "color", "phonetic": "/ˈkʌlər/", "meaning": "颜色", "sentence": "What color is it?"},
    {"word": "desk", "phonetic": "/desk/", "meaning": "课桌", "sentence": "Books are on the desk."},
    {"word": "door", "phonetic": "/dɔːr/", "meaning": "门", "sentence": "Close the door."},
    {"word": "ear", "phonetic": "/ɪr/", "meaning": "耳朵", "sentence": "I have two ears."},
    {"word": "family", "phonetic": "/ˈfæməli/", "meaning": "家庭", "sentence": "I love my family."},
    {"word": "flower", "phonetic": "/ˈflaʊər/", "meaning": "花", "sentence": "The flower is beautiful."},
    {"word": "friend", "phonetic": "/frend/", "meaning": "朋友", "sentence": "She is my friend."},
    {"word": "happy", "phonetic": "/ˈhæpi/", "meaning": "快乐的", "sentence": "I am happy."},
    {"word": "hot", "phonetic": "/hɒt/", "meaning": "热的", "sentence": "The water is hot."},
    {"word": "leaf", "phonetic": "/liːf/", "meaning": "叶子", "sentence": "The leaf is green."},
    {"word": "monkey", "phonetic": "/ˈmʌŋki/", "meaning": "猴子", "sentence": "The monkey likes bananas."},
    {"word": "mouth", "phonetic": "/maʊθ/", "meaning": "嘴巴", "sentence": "Open your mouth."},
    {"word": "new", "phonetic": "/njuː/", "meaning": "新的", "sentence": "I have a new bag."},
    {"word": "rain", "phonetic": "/reɪn/", "meaning": "雨", "sentence": "It is raining."},
    {"word": "rabbit", "phonetic": "/ˈræbɪt/", "meaning": "兔子", "sentence": "The rabbit is white."},
    {"word": "school", "phonetic": "/skuːl/", "meaning": "学校", "sentence": "I go to school."},
    {"word": "sister", "phonetic": "/ˈsɪstər/", "meaning": "姐妹", "sentence": "She is my sister."},
    {"word": "small", "phonetic": "/smɔːl/", "meaning": "小的", "sentence": "The ant is small."},
    {"word": "star", "phonetic": "/stɑːr/", "meaning": "星星", "sentence": "I can see a star."},
    {"word": "window", "phonetic": "/ˈwɪndoʊ/", "meaning": "窗户", "sentence": "Open the window."}
  ],
  "3": [
    {"word": "animal", "phonetic": "/ˈænɪməl/", "meaning": "动物", "sentence": "I like animals."},
    {"word": "bear", "phonetic": "/ber/", "meaning": "熊", "sentence": "The bear is big."},
    {"word": "beautiful", "phonetic": "/ˈbjuːtɪfəl/", "meaning": "美丽的", "sentence": "The flower is beautiful."},
    {"word": "behind", "phonetic": "/bɪˈhaɪnd/", "meaning": "在…后面", "sentence": "The cat is behind the door."},
    {"word": "between", "phonetic": "/bɪˈtwiːn/", "meaning": "在…之间", "sentence": "Sit between Tom and me."},
    {"word": "bicycle", "phonetic": "/ˈbaɪsɪkəl/", "meaning": "自行车", "sentence": "I ride a bicycle."},
    {"word": "breakfast", "phonetic": "/ˈbrekfəst/", "meaning": "早餐", "sentence": "I have breakfast at seven."},
    {"word": "carry", "phonetic": "/ˈkæri/", "meaning": "携带", "sentence": "I carry my bag."},
    {"word": "clean", "phonetic": "/kliːn/", "meaning": "干净的", "sentence": "Keep the room clean."},
    {"word": "clothes", "phonetic": "/kloʊðz/", "meaning": "衣服", "sentence": "Put on your clothes."},
    {"word": "coffee", "phonetic": "/ˈkɒfi/", "meaning": "咖啡", "sentence": "My dad likes coffee."},
    {"word": "dinner", "phonetic": "/ˈdɪnər/", "meaning": "晚餐", "sentence": "We have dinner at six."},
    {"word": "elephant", "phonetic": "/ˈelɪfənt/", "meaning": "大象", "sentence": "The elephant is very big."},
    {"word": "evening", "phonetic": "/ˈiːvnɪŋ/", "meaning": "晚上", "sentence": "Good evening!"},
    {"word": "garden", "phonetic": "/ˈɡɑːrdən/", "meaning": "花园", "sentence": "We play in the garden."},
    {"word": "giraffe", "phonetic": "/dʒɪˈræf/", "meaning": "长颈鹿", "sentence": "The giraffe is tall."},
    {"word": "homework", "phonetic": "/ˈhoʊmwɜːrk/", "meaning": "家庭作业", "sentence": "I do my homework."},
    {"word": "hungry", "phonetic": "/ˈhʌŋɡri/", "meaning": "饥饿的", "sentence": "I am hungry."},
    {"word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "meaning": "厨房", "sentence": "Mom is in the kitchen."},
    {"word": "library", "phonetic": "/ˈlaɪbrəri/", "meaning": "图书馆", "sentence": "I read books in the library."},
    {"word": "lunch", "phonetic": "/lʌntʃ/", "meaning": "午餐", "sentence": "I have lunch at noon."},
    {"word": "morning", "phonetic": "/ˈmɔːrnɪŋ/", "meaning": "早上", "sentence": "Good morning!"},
    {"word": "mountain", "phonetic": "/ˈmaʊntən/", "meaning": "山", "sentence": "The mountain is high."},
    {"word": "ocean", "phonetic": "/ˈoʊʃən/", "meaning": "海洋", "sentence": "The ocean is blue."},
    {"word": "panda", "phonetic": "/ˈpændə/", "meaning": "熊猫", "sentence": "The panda is cute."},
    {"word": "park", "phonetic": "/pɑːrk/", "meaning": "公园", "sentence": "Let's go to the park."},
    {"word": "river", "phonetic": "/ˈrɪvər/", "meaning": "河流", "sentence": "The river is long."},
    {"word": "sleep", "phonetic": "/sliːp/", "meaning": "睡觉", "sentence": "I sleep at nine."},
    {"word": "strong", "phonetic": "/strɒŋ/", "meaning": "强壮的", "sentence": "He is very strong."},
    {"word": "tiger", "phonetic": "/ˈtaɪɡər/", "meaning": "老虎", "sentence": "The tiger runs fast."}
  ],
  "4": [
    {"word": "above", "phonetic": "/əˈbʌv/", "meaning": "在…上方", "sentence": "The bird is above the tree."},
    {"word": "airport", "phonetic": "/ˈerpɔːrt/", "meaning": "机场", "sentence": "We go to the airport."},
    {"word": "bicycle", "phonetic": "/ˈbaɪsɪkəl/", "meaning": "自行车", "sentence": "He rides a bicycle to school."},
    {"word": "bridge", "phonetic": "/brɪdʒ/", "meaning": "桥", "sentence": "There is a bridge over the river."},
    {"word": "calendar", "phonetic": "/ˈkælɪndər/", "meaning": "日历", "sentence": "Look at the calendar."},
    {"word": "celebrate", "phonetic": "/ˈselɪbreɪt/", "meaning": "庆祝", "sentence": "We celebrate the New Year."},
    {"word": "cherry", "phonetic": "/ˈtʃeri/", "meaning": "樱桃", "sentence": "The cherry is red."},
    {"word": "climate", "phonetic": "/ˈklaɪmət/", "meaning": "气候", "sentence": "The climate here is warm."},
    {"word": "collect", "phonetic": "/kəˈlekt/", "meaning": "收集", "sentence": "I collect stamps."},
    {"word": "comics", "phonetic": "/ˈkɒmɪks/", "meaning": "漫画", "sentence": "I like reading comics."},
    {"word": "country", "phonetic": "/ˈkʌntri/", "meaning": "国家", "sentence": "China is a big country."},
    {"word": "dangerous", "phonetic": "/ˈdeɪndʒərəs/", "meaning": "危险的", "sentence": "The road is dangerous."},
    {"word": "different", "phonetic": "/ˈdɪfrənt/", "meaning": "不同的", "sentence": "They are different."},
    {"word": "dolphin", "phonetic": "/ˈdɒlfɪn/", "meaning": "海豚", "sentence": "The dolphin is smart."},
    {"word": "envelope", "phonetic": "/ˈenvəloʊp/", "meaning": "信封", "sentence": "Put the letter in the envelope."},
    {"word": "excellent", "phonetic": "/ˈeksələnt/", "meaning": "优秀的", "sentence": "You did an excellent job."},
    {"word": "factory", "phonetic": "/ˈfæktəri/", "meaning": "工厂", "sentence": "My father works in a factory."},
    {"word": "foreign", "phonetic": "/ˈfɒrən/", "meaning": "外国的", "sentence": "She speaks a foreign language."},
    {"word": "geography", "phonetic": "/dʒiˈɒɡrəfi/", "meaning": "地理", "sentence": "I like geography class."},
    {"word": "guitar", "phonetic": "/ɡɪˈtɑːr/", "meaning": "吉他", "sentence": "He plays the guitar."},
    {"word": "hospital", "phonetic": "/ˈhɒspɪtəl/", "meaning": "医院", "sentence": "The hospital is near here."},
    {"word": "island", "phonetic": "/ˈaɪlənd/", "meaning": "岛屿", "sentence": "We live on an island."},
    {"word": "journal", "phonetic": "/ˈdʒɜːrnl/", "meaning": "日记", "sentence": "I write in my journal."},
    {"word": "knowledge", "phonetic": "/ˈnɒlɪdʒ/", "meaning": "知识", "sentence": "Knowledge is power."},
    {"word": "language", "phonetic": "/ˈlæŋɡwɪdʒ/", "meaning": "语言", "sentence": "English is a language."},
    {"word": "museum", "phonetic": "/mjuːˈziːəm/", "meaning": "博物馆", "sentence": "We visit the museum."},
    {"word": "neighbor", "phonetic": "/ˈneɪbər/", "meaning": "邻居", "sentence": "My neighbor is friendly."},
    {"word": "password", "phonetic": "/ˈpæswɜːrd/", "meaning": "密码", "sentence": "Don't share your password."},
    {"word": "question", "phonetic": "/ˈkwestʃən/", "meaning": "问题", "sentence": "That is a good question."},
    {"word": "restaurant", "phonetic": "/ˈrestərɒnt/", "meaning": "餐厅", "sentence": "Let's eat at a restaurant."}
  ],
  "5": [
    {"word": "adventure", "phonetic": "/ədˈventʃər/", "meaning": "冒险", "sentence": "We had a great adventure."},
    {"word": "agenda", "phonetic": "/əˈdʒendə/", "meaning": "议程", "sentence": "What's on the agenda today?"},
    {"word": "ancient", "phonetic": "/ˈeɪnʃənt/", "meaning": "古老的", "sentence": "This is an ancient city."},
    {"word": "atlas", "phonetic": "/ˈætləs/", "meaning": "地图册", "sentence": "Find it in the atlas."},
    {"word": "billion", "phonetic": "/ˈbɪljən/", "meaning": "十亿", "sentence": "There are billions of stars."},
    {"word": "boundary", "phonetic": "/ˈbaʊndəri/", "meaning": "边界", "sentence": "This is the city boundary."},
    {"word": "candidate", "phonetic": "/ˈkændɪdət/", "meaning": "候选人", "sentence": "He is a good candidate."},
    {"word": "cinnamon", "phonetic": "/ˈsɪnəmən/", "meaning": "肉桂", "sentence": "Add some cinnamon."},
    {"word": "compete", "phonetic": "/kəmˈpiːt/", "meaning": "竞争", "sentence": "We compete in the race."},
    {"word": "continent", "phonetic": "/ˈkɒntɪnənt/", "meaning": "大陆", "sentence": "Asia is a continent."},
    {"word": "creature", "phonetic": "/ˈkriːtʃər/", "meaning": "生物", "sentence": "What a strange creature!"},
    {"word": "curious", "phonetic": "/ˈkjʊriəs/", "meaning": "好奇的", "sentence": "The cat is curious."},
    {"word": "decision", "phonetic": "/dɪˈsɪʒən/", "meaning": "决定", "sentence": "Make a good decision."},
    {"word": "discover", "phonetic": "/dɪˈskʌvər/", "meaning": "发现", "sentence": "We discover new things."},
    {"word": "education", "phonetic": "/ˌedʒuˈkeɪʃən/", "meaning": "教育", "sentence": "Education is important."},
    {"word": "emergency", "phonetic": "/ɪˈmɜːrdʒənsi/", "meaning": "紧急情况", "sentence": "Call in an emergency."},
    {"word": "environment", "phonetic": "/ɪnˈvaɪrənmənt/", "meaning": "环境", "sentence": "Protect the environment."},
    {"word": "explore", "phonetic": "/ɪkˈsplɔːr/", "meaning": "探索", "sentence": "Let's explore the forest."},
    {"word": "fortune", "phonetic": "/ˈfɔːrtʃən/", "meaning": "财富", "sentence": "He made a fortune."},
    {"word": "galaxy", "phonetic": "/ˈɡæləksi/", "meaning": "银河", "sentence": "The galaxy is huge."},
    {"word": "government", "phonetic": "/ˈɡʌvərnmənt/", "meaning": "政府", "sentence": "The government made a plan."},
    {"word": "harvest", "phonetic": "/ˈhɑːrvɪst/", "meaning": "收获", "sentence": "The harvest was good."},
    {"word": "headline", "phonetic": "/ˈhedlaɪn/", "meaning": "标题", "sentence": "Read the headline."},
    {"word": "imagine", "phonetic": "/ɪˈmædʒɪn/", "meaning": "想象", "sentence": "Imagine a beautiful world."},
    {"word": "journey", "phonetic": "/ˈdʒɜːrni/", "meaning": "旅程", "sentence": "It was a long journey."},
    {"word": "laboratory", "phonetic": "/ləˈbɒrətəri/", "meaning": "实验室", "sentence": "We work in the laboratory."},
    {"word": "legend", "phonetic": "/ˈledʒənd/", "meaning": "传说", "sentence": "This is an old legend."},
    {"word": "memorial", "phonetic": "/məˈmɔːriəl/", "meaning": "纪念的", "sentence": "We built a memorial."},
    {"word": "passenger", "phonetic": "/ˈpæsəndʒər/", "meaning": "乘客", "sentence": "The passengers got on the bus."},
    {"word": "universe", "phonetic": "/ˈjuːnɪvɜːrs/", "meaning": "宇宙", "sentence": "The universe is very big."}
  ],
  "6": [
    {"word": "abolish", "phonetic": "/əˈbɒlɪʃ/", "meaning": "废除", "sentence": "They decided to abolish the rule."},
    {"word": "absorb", "phonetic": "/əbˈzɔːrb/", "meaning": "吸收", "sentence": "Plants absorb water."},
    {"word": "accomplish", "phonetic": "/əˈkɒmplɪʃ/", "meaning": "完成", "sentence": "She accomplished her goal."},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的", "sentence": "The answer is accurate."},
    {"word": "ambitious", "phonetic": "/æmˈbɪʃəs/", "meaning": "有抱负的", "sentence": "He is an ambitious student."},
    {"word": "analyze", "phonetic": "/ˈænəlaɪz/", "meaning": "分析", "sentence": "Let's analyze the data."},
    {"word": "atmosphere", "phonetic": "/ˈætməsfɪr/", "meaning": "大气层", "sentence": "The atmosphere protects us."},
    {"word": "beneath", "phonetic": "/bɪˈniːθ/", "meaning": "在…下方", "sentence": "The cat is beneath the table."},
    {"word": "calculate", "phonetic": "/ˈkælkjuleɪt/", "meaning": "计算", "sentence": "Calculate the total cost."},
    {"word": "ceremony", "phonetic": "/ˈserəmoʊni/", "meaning": "典礼", "sentence": "The ceremony was beautiful."},
    {"word": "characteristic", "phonetic": "/ˌkærəktəˈrɪstɪk/", "meaning": "特征", "sentence": "Kindness is her characteristic."},
    {"word": "circumstance", "phonetic": "/ˈsɜːrkəmstæns/", "meaning": "情况", "sentence": "Under this circumstance..."},
    {"word": "civilization", "phonetic": "/ˌsɪvəlaɪˈzeɪʃən/", "meaning": "文明", "sentence": "Ancient civilization was amazing."},
    {"word": "comprehend", "phonetic": "/ˌkɒmprɪˈhend/", "meaning": "理解", "sentence": "I comprehend the lesson."},
    {"word": "consequence", "phonetic": "/ˈkɒnsɪkwəns/", "meaning": "后果", "sentence": "Think about the consequence."},
    {"word": "demonstrate", "phonetic": "/ˈdemənstreɪt/", "meaning": "展示", "sentence": "Let me demonstrate how it works."},
    {"word": "determine", "phonetic": "/dɪˈtɜːrmɪn/", "meaning": "决定", "sentence": "Determine your goal."},
    {"word": "efficient", "phonetic": "/ɪˈfɪʃənt/", "meaning": "高效的", "sentence": "This method is efficient."},
    {"word": "encyclopedia", "phonetic": "/ɪnˌsaɪkləˈpiːdiə/", "meaning": "百科全书", "sentence": "Look it up in the encyclopedia."},
    {"word": "evolution", "phonetic": "/ˌiːvəˈluːʃən/", "meaning": "进化", "sentence": "Evolution is a slow process."},
    {"word": "experiment", "phonetic": "/ɪkˈsperɪmənt/", "meaning": "实验", "sentence": "We did an experiment."},
    {"word": "generation", "phonetic": "/ˌdʒenəˈreɪʃən/", "meaning": "一代人", "sentence": "The new generation is smart."},
    {"word": "hypothesis", "phonetic": "/haɪˈpɒθəsɪs/", "meaning": "假设", "sentence": "This is our hypothesis."},
    {"word": "investigate", "phonetic": "/ɪnˈvestɪɡeɪt/", "meaning": "调查", "sentence": "We investigate the problem."},
    {"word": "magnificent", "phonetic": "/mæɡˈnɪfɪsənt/", "meaning": "壮丽的", "sentence": "The view is magnificent."},
    {"word": "nutrient", "phonetic": "/ˈnjuːtriənt/", "meaning": "营养物", "sentence": "Vegetables have many nutrients."},
    {"word": "phenomenon", "phonetic": "/fɪˈnɒmɪnən/", "meaning": "现象", "sentence": "It is a strange phenomenon."},
    {"word": "satellite", "phonetic": "/ˈsætəlaɪt/", "meaning": "卫星", "sentence": "The moon is a satellite."},
    {"word": "strategy", "phonetic": "/ˈstrætədʒi/", "meaning": "策略", "sentence": "We need a new strategy."},
    {"word": "vocabulary", "phonetic": "/voʊˈkæbjəleri/", "meaning": "词汇", "sentence": "Learn new vocabulary every day."}
  ]
}
