export const wordsDB = {
  "1": [
    {"word": "apple", "phonetic": "/ˈæpəl/", "meaning": "苹果", "sentence": "I like apples."},
    {"word": "cat", "phonetic": "/kæt/", "meaning": "猫", "sentence": "The cat is cute."},
    {"word": "dog", "phonetic": "/dɒɡ/", "meaning": "狗", "sentence": "I have a dog."},
    {"word": "egg", "phonetic": "/eɡ/", "meaning": "鸡蛋", "sentence": "I eat an egg every day."},
    {"word": "fish", "phonetic": "/fɪʃ/", "meaning": "鱼", "sentence": "The fish can swim."},
    {"word": "girl", "phonetic": "/ɡɜːrl/", "meaning": "女孩", "sentence": "She is a good girl."},
    {"word": "hand", "phonetic": "/hænd/", "meaning": "手", "sentence": "Wash your hands."},
    {"word": "ice", "phonetic": "/aɪs/", "meaning": "冰", "sentence": "The ice is cold."},
    {"word": "juice", "phonetic": "/dʒuːs/", "meaning": "果汁", "sentence": "I like orange juice."},
    {"word": "kite", "phonetic": "/kaɪt/", "meaning": "风筝", "sentence": "Let's fly a kite."},
    {"word": "lion", "phonetic": "/ˈlaɪən/", "meaning": "狮子", "sentence": "The lion is strong."},
    {"word": "milk", "phonetic": "/mɪlk/", "meaning": "牛奶", "sentence": "I drink milk every morning."},
    {"word": "nose", "phonetic": "/noʊz/", "meaning": "鼻子", "sentence": "Touch your nose."},
    {"word": "orange", "phonetic": "/ˈɒrɪndʒ/", "meaning": "橙子", "sentence": "The orange is sweet."},
    {"word": "pen", "phonetic": "/pen/", "meaning": "钢笔", "sentence": "This is my pen."},
    {"word": "queen", "phonetic": "/kwiːn/", "meaning": "女王", "sentence": "She is the queen."},
    {"word": "red", "phonetic": "/red/", "meaning": "红色", "sentence": "The apple is red."},
    {"word": "sun", "phonetic": "/sʌn/", "meaning": "太阳", "sentence": "The sun is bright."},
    {"word": "tree", "phonetic": "/triː/", "meaning": "树", "sentence": "There is a big tree."},
    {"word": "umbrella", "phonetic": "/ʌmˈbrelə/", "meaning": "雨伞", "sentence": "Take your umbrella."},
    {"word": "van", "phonetic": "/væn/", "meaning": "面包车", "sentence": "The van is white."},
    {"word": "water", "phonetic": "/ˈwɔːtər/", "meaning": "水", "sentence": "I drink water."},
    {"word": "box", "phonetic": "/bɒks/", "meaning": "盒子", "sentence": "Put it in the box."},
    {"word": "yellow", "phonetic": "/ˈjeloʊ/", "meaning": "黄色", "sentence": "The banana is yellow."},
    {"word": "zoo", "phonetic": "/zuː/", "meaning": "动物园", "sentence": "Let's go to the zoo."},
    {"word": "book", "phonetic": "/bʊk/", "meaning": "书", "sentence": "I read a book."},
    {"word": "cake", "phonetic": "/keɪk/", "meaning": "蛋糕", "sentence": "The cake is yummy."},
    {"word": "duck", "phonetic": "/dʌk/", "meaning": "鸭子", "sentence": "The duck can swim."},
    {"word": "eye", "phonetic": "/aɪ/", "meaning": "眼睛", "sentence": "I have two eyes."},
    {"word": "foot", "phonetic": "/fʊt/", "meaning": "脚", "sentence": "I hurt my foot."}
  ],
  "2": [
    {"word": "bag", "phonetic": "/bæɡ/", "meaning": "书包", "sentence": "My bag is blue."},
    {"word": "big", "phonetic": "/bɪɡ/", "meaning": "大的", "sentence": "The elephant is big."},
    {"word": "bird", "phonetic": "/bɜːrd/", "meaning": "鸟", "sentence": "The bird can fly."},
    {"word": "bread", "phonetic": "/bred/", "meaning": "面包", "sentence": "I eat bread for breakfast."},
    {"word": "brother", "phonetic": "/ˈbrʌðər/", "meaning": "兄弟", "sentence": "He is my brother."},
    {"word": "candy", "phonetic": "/ˈkændi/", "meaning": "糖果", "sentence": "I like candy."},
    {"word": "chair", "phonetic": "/tʃer/", "meaning": "椅子", "sentence": "Sit on the chair."},
    {"word": "chicken", "phonetic": "/ˈtʃɪkɪn/", "meaning": "鸡", "sentence": "I like chicken."},
    {"word": "cloud", "phonetic": "/klaʊd/", "meaning": "云", "sentence": "Look at the cloud."},
    {"word": "cold", "phonetic": "/koʊld/", "meaning": "冷的", "sentence": "It is cold today."},
    {"word": "color", "phonetic": "/ˈkʌlər/", "meaning": "颜色", "sentence": "What color is it?"},
    {"word": "desk", "phonetic": "/desk/", "meaning": "课桌", "sentence": "Books are on the desk."},
    {"word": "door", "phonetic": "/dɔːr/", "meaning": "门", "sentence": "Close the door."},
    {"word": "ear", "phonetic": "/ɪr/", "meaning": "耳朵", "sentence": "I have two ears."},
    {"word": "family", "phonetic": "/ˈfæməli/", "meaning": "家庭", "sentence": "I love my family."},
    {"word": "flower", "phonetic": "/ˈflaʊər/", "meaning": "花", "sentence": "The flower is beautiful."},
    {"word": "friend", "phonetic": "/frend/", "meaning": "朋友", "sentence": "She is my friend."},
    {"word": "happy", "phonetic": "/ˈhæpi/", "meaning": "快乐的", "sentence": "I am happy."},
    {"word": "hot", "phonetic": "/hɒt/", "meaning": "热的", "sentence": "The water is hot."},
    {"word": "leaf", "phonetic": "/liːf/", "meaning": "叶子", "sentence": "The leaf is green."},
    {"word": "monkey", "phonetic": "/ˈmʌŋki/", "meaning": "猴子", "sentence": "The monkey likes bananas."},
    {"word": "mouth", "phonetic": "/maʊθ/", "meaning": "嘴巴", "sentence": "Open your mouth."},
    {"word": "new", "phonetic": "/njuː/", "meaning": "新的", "sentence": "I have a new bag."},
    {"word": "rain", "phonetic": "/reɪn/", "meaning": "雨", "sentence": "It is raining."},
    {"word": "rabbit", "phonetic": "/ˈræbɪt/", "meaning": "兔子", "sentence": "The rabbit is white."},
    {"word": "school", "phonetic": "/skuːl/", "meaning": "学校", "sentence": "I go to school."},
    {"word": "sister", "phonetic": "/ˈsɪstər/", "meaning": "姐妹", "sentence": "She is my sister."},
    {"word": "small", "phonetic": "/smɔːl/", "meaning": "小的", "sentence": "The ant is small."},
    {"word": "star", "phonetic": "/stɑːr/", "meaning": "星星", "sentence": "I can see a star."},
    {"word": "window", "phonetic": "/ˈwɪndoʊ/", "meaning": "窗户", "sentence": "Open the window."}
  ],
  "3": [
    {"word": "animal", "phonetic": "/ˈænɪməl/", "meaning": "动物", "sentence": "I like animals."},
    {"word": "bear", "phonetic": "/ber/", "meaning": "熊", "sentence": "The bear is big."},
    {"word": "beautiful", "phonetic": "/ˈbjuːtɪfəl/", "meaning": "美丽的", "sentence": "The flower is beautiful."},
    {"word": "behind", "phonetic": "/bɪˈhaɪnd/", "meaning": "在…后面", "sentence": "The cat is behind the door."},
    {"word": "between", "phonetic": "/bɪˈtwiːn/", "meaning": "在…之间", "sentence": "Sit between Tom and me."},
    {"word": "bicycle", "phonetic": "/ˈbaɪsɪkəl/", "meaning": "自行车", "sentence": "I ride a bicycle."},
    {"word": "breakfast", "phonetic": "/ˈbrekfəst/", "meaning": "早餐", "sentence": "I have breakfast at seven."},
    {"word": "carry", "phonetic": "/ˈkæri/", "meaning": "携带", "sentence": "I carry my bag."},
    {"word": "clean", "phonetic": "/kliːn/", "meaning": "干净的", "sentence": "Keep the room clean."},
    {"word": "clothes", "phonetic": "/kloʊðz/", "meaning": "衣服", "sentence": "Put on your clothes."},
    {"word": "coffee", "phonetic": "/ˈkɒfi/", "meaning": "咖啡", "sentence": "My dad likes coffee."},
    {"word": "dinner", "phonetic": "/ˈdɪnər/", "meaning": "晚餐", "sentence": "We have dinner at six."},
    {"word": "elephant", "phonetic": "/ˈelɪfənt/", "meaning": "大象", "sentence": "The elephant is very big."},
    {"word": "evening", "phonetic": "/ˈiːvnɪŋ/", "meaning": "晚上", "sentence": "Good evening!"},
    {"word": "garden", "phonetic": "/ˈɡɑːrdən/", "meaning": "花园", "sentence": "We play in the garden."},
    {"word": "giraffe", "phonetic": "/dʒɪˈræf/", "meaning": "长颈鹿", "sentence": "The giraffe is tall."},
    {"word": "homework", "phonetic": "/ˈhoʊmwɜːrk/", "meaning": "家庭作业", "sentence": "I do my homework."},
    {"word": "hungry", "phonetic": "/ˈhʌŋɡri/", "meaning": "饥饿的", "sentence": "I am hungry."},
    {"word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "meaning": "厨房", "sentence": "Mom is in the kitchen."},
    {"word": "library", "phonetic": "/ˈlaɪbrəri/", "meaning": "图书馆", "sentence": "I read books in the library."},
    {"word": "lunch", "phonetic": "/lʌntʃ/", "meaning": "午餐", "sentence": "I have lunch at noon."},
    {"word": "morning", "phonetic": "/ˈmɔːrnɪŋ/", "meaning": "早上", "sentence": "Good morning!"},
    {"word": "mountain", "phonetic": "/ˈmaʊntən/", "meaning": "山", "sentence": "The mountain is high."},
    {"word": "ocean", "phonetic": "/ˈoʊʃən/", "meaning": "海洋", "sentence": "The ocean is blue."},
    {"word": "panda", "phonetic": "/ˈpændə/", "meaning": "熊猫", "sentence": "The panda is cute."},
    {"word": "park", "phonetic": "/pɑːrk/", "meaning": "公园", "sentence": "Let's go to the park."},
    {"word": "river", "phonetic": "/ˈrɪvər/", "meaning": "河流", "sentence": "The river is long."},
    {"word": "sleep", "phonetic": "/sliːp/", "meaning": "睡觉", "sentence": "I sleep at nine."},
    {"word": "strong", "phonetic": "/strɒŋ/", "meaning": "强壮的", "sentence": "He is very strong."},
    {"word": "tiger", "phonetic": "/ˈtaɪɡər/", "meaning": "老虎", "sentence": "The tiger runs fast."}
  ],
  "4": [
    {"word": "above", "phonetic": "/əˈbʌv/", "meaning": "在…上方", "sentence": "The bird is above the tree."},
    {"word": "airport", "phonetic": "/ˈerpɔːrt/", "meaning": "机场", "sentence": "We go to the airport."},
    {"word": "bicycle", "phonetic": "/ˈbaɪsɪkəl/", "meaning": "自行车", "sentence": "He rides a bicycle to school."},
    {"word": "bridge", "phonetic": "/brɪdʒ/", "meaning": "桥", "sentence": "There is a bridge over the river."},
    {"word": "calendar", "phonetic": "/ˈkælɪndər/", "meaning": "日历", "sentence": "Look at the calendar."},
    {"word": "celebrate", "phonetic": "/ˈselɪbreɪt/", "meaning": "庆祝", "sentence": "We celebrate the New Year."},
    {"word": "cherry", "phonetic": "/ˈtʃeri/", "meaning": "樱桃", "sentence": "The cherry is red."},
    {"word": "climate", "phonetic": "/ˈklaɪmət/", "meaning": "气候", "sentence": "The climate here is warm."},
    {"word": "collect", "phonetic": "/kəˈlekt/", "meaning": "收集", "sentence": "I collect stamps."},
    {"word": "comics", "phonetic": "/ˈkɒmɪks/", "meaning": "漫画", "sentence": "I like reading comics."},
    {"word": "country", "phonetic": "/ˈkʌntri/", "meaning": "国家", "sentence": "China is a big country."},
    {"word": "dangerous", "phonetic": "/ˈdeɪndʒərəs/", "meaning": "危险的", "sentence": "The road is dangerous."},
    {"word": "different", "phonetic": "/ˈdɪfrənt/", "meaning": "不同的", "sentence": "They are different."},
    {"word": "dolphin", "phonetic": "/ˈdɒlfɪn/", "meaning": "海豚", "sentence": "The dolphin is smart."},
    {"word": "envelope", "phonetic": "/ˈenvəloʊp/", "meaning": "信封", "sentence": "Put the letter in the envelope."},
    {"word": "excellent", "phonetic": "/ˈeksələnt/", "meaning": "优秀的", "sentence": "You did an excellent job."},
    {"word": "factory", "phonetic": "/ˈfæktəri/", "meaning": "工厂", "sentence": "My father works in a factory."},
    {"word": "foreign", "phonetic": "/ˈfɒrən/", "meaning": "外国的", "sentence": "She speaks a foreign language."},
    {"word": "geography", "phonetic": "/dʒiˈɒɡrəfi/", "meaning": "地理", "sentence": "I like geography class."},
    {"word": "guitar", "phonetic": "/ɡɪˈtɑːr/", "meaning": "吉他", "sentence": "He plays the guitar."},
    {"word": "hospital", "phonetic": "/ˈhɒspɪtəl/", "meaning": "医院", "sentence": "The hospital is near here."},
    {"word": "island", "phonetic": "/ˈaɪlənd/", "meaning": "岛屿", "sentence": "We live on an island."},
    {"word": "journal", "phonetic": "/ˈdʒɜːrnl/", "meaning": "日记", "sentence": "I write in my journal."},
    {"word": "knowledge", "phonetic": "/ˈnɒlɪdʒ/", "meaning": "知识", "sentence": "Knowledge is power."},
    {"word": "language", "phonetic": "/ˈlæŋɡwɪdʒ/", "meaning": "语言", "sentence": "English is a language."},
    {"word": "museum", "phonetic": "/mjuːˈziːəm/", "meaning": "博物馆", "sentence": "We visit the museum."},
    {"word": "neighbor", "phonetic": "/ˈneɪbər/", "meaning": "邻居", "sentence": "My neighbor is friendly."},
    {"word": "password", "phonetic": "/ˈpæswɜːrd/", "meaning": "密码", "sentence": "Don't share your password."},
    {"word": "question", "phonetic": "/ˈkwestʃən/", "meaning": "问题", "sentence": "That is a good question."},
    {"word": "restaurant", "phonetic": "/ˈrestərɒnt/", "meaning": "餐厅", "sentence": "Let's eat at a restaurant."}
  ],
  "5": [
    {"word": "tidy", "phonetic": "/ˈtaɪdi/", "meaning": "整理；整洁的", "sentence": "Please tidy your room."},
    {"word": "mess", "phonetic": "/mes/", "meaning": "脏乱；不整洁", "sentence": "What a mess!"},
    {"word": "sock", "phonetic": "/sɒk/", "meaning": "短袜", "sentence": "I need a pair of socks."},
    {"word": "yours", "phonetic": "/jɔːz/", "meaning": "你的；你们的", "sentence": "Is this pen yours?"},
    {"word": "cap", "phonetic": "/kæp/", "meaning": "帽子", "sentence": "He wears a red cap."},
    {"word": "mine", "phonetic": "/maɪn/", "meaning": "我的", "sentence": "This book is mine."},
    {"word": "crayon", "phonetic": "/ˈkreɪən/", "meaning": "彩色蜡笔", "sentence": "I draw with crayons."},
    {"word": "umbrella", "phonetic": "/ʌmˈbrelə/", "meaning": "伞", "sentence": "Take your umbrella."},
    {"word": "nail", "phonetic": "/neɪl/", "meaning": "钉子", "sentence": "There is a nail in the wall."},
    {"word": "drop", "phonetic": "/drɒp/", "meaning": "使落下；掉落", "sentence": "Don't drop the glass."},
    {"word": "stick", "phonetic": "/stɪk/", "meaning": "粘贴；粘住", "sentence": "Stick the picture on the wall."},
    {"word": "second", "phonetic": "/ˈsekənd/", "meaning": "秒", "sentence": "Wait a second, please."},
    {"word": "hers", "phonetic": "/hɜːz/", "meaning": "她的", "sentence": "The bag is hers."},
    {"word": "theirs", "phonetic": "/ðeəz/", "meaning": "他们的", "sentence": "The toys are theirs."},
    {"word": "why", "phonetic": "/waɪ/", "meaning": "为什么", "sentence": "Why are you late?"},
    {"word": "because", "phonetic": "/bɪˈkɒz/", "meaning": "因为", "sentence": "I'm happy because it's sunny."},
    {"word": "study", "phonetic": "/ˈstʌdi/", "meaning": "书房；学习", "sentence": "He reads in the study."},
    {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "改变；变化", "sentence": "The leaves change colour."},
    {"word": "place", "phonetic": "/pleɪs/", "meaning": "地方", "sentence": "This is a nice place."},
    {"word": "twice", "phonetic": "/twaɪs/", "meaning": "两次", "sentence": "I brush my teeth twice a day."},
    {"word": "every", "phonetic": "/ˈevri/", "meaning": "每；每个", "sentence": "I go to school every day."},
    {"word": "north", "phonetic": "/nɔːθ/", "meaning": "北方；向北", "sentence": "Beijing is in the north."},
    {"word": "south", "phonetic": "/saʊθ/", "meaning": "南方；向南", "sentence": "Guangzhou is in the south."},
    {"word": "enough", "phonetic": "/ɪˈnʌf/", "meaning": "足够的", "sentence": "Do you have enough water?"},
    {"word": "future", "phonetic": "/ˈfjuːtʃə/", "meaning": "将来；未来", "sentence": "I want to be a doctor in the future."},
    {"word": "stand", "phonetic": "/stænd/", "meaning": "站；站立", "sentence": "Please stand up."},
    {"word": "machine", "phonetic": "/məˈʃiːn/", "meaning": "机器", "sentence": "This machine makes toys."},
    {"word": "will", "phonetic": "/wɪl/", "meaning": "将；将会", "sentence": "I will go to school tomorrow."},
    {"word": "exercise", "phonetic": "/ˈeksəsaɪz/", "meaning": "运动；锻炼", "sentence": "Let's do some exercise."},
    {"word": "early", "phonetic": "/ˈɜːli/", "meaning": "早；提早", "sentence": "I get up early every day."},
    {"word": "easily", "phonetic": "/ˈiːzəli/", "meaning": "容易地", "sentence": "I can do it easily."},
    {"word": "hard", "phonetic": "/hɑːd/", "meaning": "努力地", "sentence": "She studies hard."},
    {"word": "more", "phonetic": "/mɔː/", "meaning": "更多的", "sentence": "I need more time."},
    {"word": "storybook", "phonetic": "/ˈstɔːribʊk/", "meaning": "故事书", "sentence": "I like reading storybooks."},
    {"word": "buy", "phonetic": "/baɪ/", "meaning": "买", "sentence": "I want to buy a book."},
    {"word": "dictionary", "phonetic": "/ˈdɪkʃənəri/", "meaning": "字典；词典", "sentence": "Look it up in the dictionary."},
    {"word": "magazine", "phonetic": "/ˌmæɡəˈziːn/", "meaning": "杂志", "sentence": "I read a magazine."},
    {"word": "newspaper", "phonetic": "/ˈnjuːzpeɪpə/", "meaning": "报纸", "sentence": "Dad reads the newspaper."},
    {"word": "week", "phonetic": "/wiːk/", "meaning": "周；星期", "sentence": "There are seven days in a week."},
    {"word": "poster", "phonetic": "/ˈpəʊstə/", "meaning": "海报", "sentence": "We make a poster."},
    {"word": "best", "phonetic": "/best/", "meaning": "最好的", "sentence": "She is my best friend."},
    {"word": "writer", "phonetic": "/ˈraɪtə/", "meaning": "作家", "sentence": "He is a famous writer."},
    {"word": "weekend", "phonetic": "/ˌwiːkˈend/", "meaning": "周末", "sentence": "What do you do at the weekend?"},
    {"word": "stay", "phonetic": "/steɪ/", "meaning": "待；逗留", "sentence": "I stay at home on Sunday."},
    {"word": "film", "phonetic": "/fɪlm/", "meaning": "电影", "sentence": "Let's see a film."},
    {"word": "boat", "phonetic": "/bəʊt/", "meaning": "小船", "sentence": "We row a boat on the lake."},
    {"word": "plan", "phonetic": "/plæn/", "meaning": "安排；计划", "sentence": "I plan to visit my grandma."},
    {"word": "tomorrow", "phonetic": "/təˈmɒrəʊ/", "meaning": "明天", "sentence": "I will go to the park tomorrow."},
    {"word": "build", "phonetic": "/bɪld/", "meaning": "建筑；建造", "sentence": "They build a new house."},
    {"word": "swing", "phonetic": "/swɪŋ/", "meaning": "秋千", "sentence": "She plays on the swing."},
    {"word": "cry", "phonetic": "/kraɪ/", "meaning": "哭；喊叫", "sentence": "Don't cry, be brave."},
    {"word": "until", "phonetic": "/ənˈtɪl/", "meaning": "直到", "sentence": "Wait until I come back."},
    {"word": "holiday", "phonetic": "/ˈhɒlədi/", "meaning": "假日；假期", "sentence": "We go to the beach on holiday."},
    {"word": "clear", "phonetic": "/klɪə/", "meaning": "清澈的", "sentence": "The water is very clear."},
    {"word": "seafood", "phonetic": "/ˈsiːfuːd/", "meaning": "海鲜", "sentence": "I like eating seafood."},
    {"word": "hotel", "phonetic": "/həʊˈtel/", "meaning": "旅馆", "sentence": "We stay in a hotel."},
    {"word": "island", "phonetic": "/ˈaɪlənd/", "meaning": "岛", "sentence": "There is a small island."},
    {"word": "butterfly", "phonetic": "/ˈbʌtəflaɪ/", "meaning": "蝴蝶", "sentence": "The butterfly is beautiful."},
    {"word": "meet", "phonetic": "/miːt/", "meaning": "迎接；会见", "sentence": "I meet my friends at the gate."},
    {"word": "hall", "phonetic": "/hɔːl/", "meaning": "礼堂", "sentence": "We have a show in the hall."},
    {"word": "finally", "phonetic": "/ˈfaɪnəli/", "meaning": "最后", "sentence": "Finally, we go home."},
    {"word": "show", "phonetic": "/ʃəʊ/", "meaning": "给…看；展示", "sentence": "Show me your picture."},
    {"word": "project", "phonetic": "/ˈprɒdʒekt/", "meaning": "课题；项目", "sentence": "We do a project about animals."},
    {"word": "board", "phonetic": "/bɔːd/", "meaning": "布告牌；木板", "sentence": "Look at the board, please."},
    {"word": "which", "phonetic": "/wɪtʃ/", "meaning": "哪一个", "sentence": "Which one do you like?"},
    {"word": "size", "phonetic": "/saɪz/", "meaning": "尺码", "sentence": "What size do you wear?"},
    {"word": "sweater", "phonetic": "/ˈswetə/", "meaning": "毛衣", "sentence": "Put on your sweater."},
    {"word": "trousers", "phonetic": "/ˈtraʊzəz/", "meaning": "裤子", "sentence": "He wears black trousers."},
    {"word": "coat", "phonetic": "/kəʊt/", "meaning": "外套；大衣", "sentence": "It's cold. Wear your coat."},
    {"word": "shoe", "phonetic": "/ʃuː/", "meaning": "鞋", "sentence": "My shoes are new."},
    {"word": "emperor", "phonetic": "/ˈempərə/", "meaning": "皇帝", "sentence": "The emperor has new clothes."},
    {"word": "only", "phonetic": "/ˈəʊnli/", "meaning": "只有；仅", "sentence": "I have only one pen."},
    {"word": "nod", "phonetic": "/nɒd/", "meaning": "点头", "sentence": "She nods her head."},
    {"word": "smile", "phonetic": "/smaɪl/", "meaning": "笑容；微笑", "sentence": "She has a big smile."},
    {"word": "money", "phonetic": "/ˈmʌni/", "meaning": "钱", "sentence": "How much money do you have?"},
    {"word": "keep", "phonetic": "/kiːp/", "meaning": "保持", "sentence": "Keep your room clean."},
    {"word": "laugh", "phonetic": "/lɑːf/", "meaning": "大笑", "sentence": "The story makes us laugh."},
    {"word": "ill", "phonetic": "/ɪl/", "meaning": "生病的；不舒服", "sentence": "She is ill today."},
    {"word": "wrong", "phonetic": "/rɒŋ/", "meaning": "有毛病；不正常", "sentence": "What's wrong with you?"},
    {"word": "headache", "phonetic": "/ˈhedeɪk/", "meaning": "头痛", "sentence": "I have a headache."},
    {"word": "fever", "phonetic": "/ˈfiːvə/", "meaning": "发烧", "sentence": "She has a high fever."},
    {"word": "should", "phonetic": "/ʃʊd/", "meaning": "应该", "sentence": "You should drink more water."},
    {"word": "medicine", "phonetic": "/ˈmedsən/", "meaning": "药", "sentence": "Take some medicine."},
    {"word": "rest", "phonetic": "/rest/", "meaning": "休息", "sentence": "Have a good rest."},
    {"word": "toothache", "phonetic": "/ˈtuːθeɪk/", "meaning": "牙痛", "sentence": "I have a toothache."},
    {"word": "invention", "phonetic": "/ɪnˈvenʃən/", "meaning": "发明；创造", "sentence": "Paper is a great invention."},
    {"word": "invent", "phonetic": "/ɪnˈvent/", "meaning": "发明", "sentence": "He invents a new machine."},
    {"word": "travel", "phonetic": "/ˈtrævəl/", "meaning": "旅行", "sentence": "I like to travel."},
    {"word": "anywhere", "phonetic": "/ˈeniweə/", "meaning": "任何地方", "sentence": "You can go anywhere."},
    {"word": "camera", "phonetic": "/ˈkæmərə/", "meaning": "照相机", "sentence": "Take a photo with the camera."},
    {"word": "myself", "phonetic": "/maɪˈself/", "meaning": "我自己", "sentence": "I can do it myself."},
    {"word": "festival", "phonetic": "/ˈfestɪvəl/", "meaning": "节日", "sentence": "The Spring Festival is coming."},
    {"word": "important", "phonetic": "/ɪmˈpɔːtənt/", "meaning": "重要的", "sentence": "English is very important."},
    {"word": "dumpling", "phonetic": "/ˈdʌmplɪŋ/", "meaning": "饺子", "sentence": "We eat dumplings at the Spring Festival."},
    {"word": "relative", "phonetic": "/ˈrelətɪv/", "meaning": "亲戚", "sentence": "I visit my relatives."},
    {"word": "firework", "phonetic": "/ˈfaɪəwɜːk/", "meaning": "烟花", "sentence": "We watch fireworks at night."},
    {"word": "giant", "phonetic": "/ˈdʒaɪənt/", "meaning": "巨人", "sentence": "The giant lives in a castle."},
    {"word": "garden", "phonetic": "/ˈɡɑːdən/", "meaning": "花园", "sentence": "The garden is full of flowers."},
    {"word": "castle", "phonetic": "/ˈkɑːsəl/", "meaning": "城堡", "sentence": "There is a big castle on the hill."},
    {"word": "through", "phonetic": "/θruː/", "meaning": "穿过", "sentence": "Walk through the door."},
    {"word": "kind", "phonetic": "/kaɪnd/", "meaning": "善良的", "sentence": "She is very kind to everyone."}
  ],
  "6": [
    {"word": "abolish", "phonetic": "/əˈbɒlɪʃ/", "meaning": "废除", "sentence": "They decided to abolish the rule."},
    {"word": "absorb", "phonetic": "/əbˈzɔːrb/", "meaning": "吸收", "sentence": "Plants absorb water."},
    {"word": "accomplish", "phonetic": "/əˈkɒmplɪʃ/", "meaning": "完成", "sentence": "She accomplished her goal."},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的", "sentence": "The answer is accurate."},
    {"word": "ambitious", "phonetic": "/æmˈbɪʃəs/", "meaning": "有抱负的", "sentence": "He is an ambitious student."},
    {"word": "analyze", "phonetic": "/ˈænəlaɪz/", "meaning": "分析", "sentence": "Let's analyze the data."},
    {"word": "atmosphere", "phonetic": "/ˈætməsfɪr/", "meaning": "大气层", "sentence": "The atmosphere protects us."},
    {"word": "beneath", "phonetic": "/bɪˈniːθ/", "meaning": "在…下方", "sentence": "The cat is beneath the table."},
    {"word": "calculate", "phonetic": "/ˈkælkjuleɪt/", "meaning": "计算", "sentence": "Calculate the total cost."},
    {"word": "ceremony", "phonetic": "/ˈserəmoʊni/", "meaning": "典礼", "sentence": "The ceremony was beautiful."},
    {"word": "characteristic", "phonetic": "/ˌkærəktəˈrɪstɪk/", "meaning": "特征", "sentence": "Kindness is her characteristic."},
    {"word": "circumstance", "phonetic": "/ˈsɜːrkəmstæns/", "meaning": "情况", "sentence": "Under this circumstance..."},
    {"word": "civilization", "phonetic": "/ˌsɪvəlaɪˈzeɪʃən/", "meaning": "文明", "sentence": "Ancient civilization was amazing."},
    {"word": "comprehend", "phonetic": "/ˌkɒmprɪˈhend/", "meaning": "理解", "sentence": "I comprehend the lesson."},
    {"word": "consequence", "phonetic": "/ˈkɒnsɪkwəns/", "meaning": "后果", "sentence": "Think about the consequence."},
    {"word": "demonstrate", "phonetic": "/ˈdemənstreɪt/", "meaning": "展示", "sentence": "Let me demonstrate how it works."},
    {"word": "determine", "phonetic": "/dɪˈtɜːrmɪn/", "meaning": "决定", "sentence": "Determine your goal."},
    {"word": "efficient", "phonetic": "/ɪˈfɪʃənt/", "meaning": "高效的", "sentence": "This method is efficient."},
    {"word": "encyclopedia", "phonetic": "/ɪnˌsaɪkləˈpiːdiə/", "meaning": "百科全书", "sentence": "Look it up in the encyclopedia."},
    {"word": "evolution", "phonetic": "/ˌiːvəˈluːʃən/", "meaning": "进化", "sentence": "Evolution is a slow process."},
    {"word": "experiment", "phonetic": "/ɪkˈsperɪmənt/", "meaning": "实验", "sentence": "We did an experiment."},
    {"word": "generation", "phonetic": "/ˌdʒenəˈreɪʃən/", "meaning": "一代人", "sentence": "The new generation is smart."},
    {"word": "hypothesis", "phonetic": "/haɪˈpɒθəsɪs/", "meaning": "假设", "sentence": "This is our hypothesis."},
    {"word": "investigate", "phonetic": "/ɪnˈvestɪɡeɪt/", "meaning": "调查", "sentence": "We investigate the problem."},
    {"word": "magnificent", "phonetic": "/mæɡˈnɪfɪsənt/", "meaning": "壮丽的", "sentence": "The view is magnificent."},
    {"word": "nutrient", "phonetic": "/ˈnjuːtriənt/", "meaning": "营养物", "sentence": "Vegetables have many nutrients."},
    {"word": "phenomenon", "phonetic": "/fɪˈnɒmɪnən/", "meaning": "现象", "sentence": "It is a strange phenomenon."},
    {"word": "satellite", "phonetic": "/ˈsætəlaɪt/", "meaning": "卫星", "sentence": "The moon is a satellite."},
    {"word": "strategy", "phonetic": "/ˈstrætədʒi/", "meaning": "策略", "sentence": "We need a new strategy."},
    {"word": "vocabulary", "phonetic": "/voʊˈkæbjəleri/", "meaning": "词汇", "sentence": "Learn new vocabulary every day."}
  ]
}
